# The directory from which notification templates are read.
templates: 
- '/etc/alertmanager/template/*.tmpl'

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default

receivers:
- name: default

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
# We use this to mute any warning-level notifications if the same alert is 
# already critical.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'cluster', 'service']
